# Generated by Django 4.0.2 on 2022-02-24 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCatgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BlogTages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_titel', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='img')),
                ('desc', models.TextField()),
                ('date', models.DateField()),
                ('client', models.CharField(max_length=150)),
                ('project_domain', models.CharField(max_length=200)),
                ('project_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('st_end_year', models.CharField(max_length=250)),
                ('project_name', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('import_word1', models.CharField(max_length=250)),
                ('import_mord2', models.CharField(max_length=250)),
                ('import_word3', models.CharField(max_length=250)),
                ('short_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img')),
                ('rol1', models.CharField(max_length=150)),
                ('rol2', models.CharField(max_length=150)),
                ('rol3', models.CharField(max_length=150)),
                ('desc', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='img')),
                ('words', models.TextField()),
                ('fb_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Detail_opations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=250)),
                ('desc', models.TextField()),
                ('protfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Bloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=250)),
                ('author_name', models.CharField(max_length=200)),
                ('deate', models.DateField()),
                ('video', models.URLField()),
                ('desc', models.TextField()),
                ('quotes', models.TextField()),
                ('author_img', models.ImageField(upload_to='img')),
                ('comment_word', models.TextField()),
                ('fb_link', models.URLField()),
                ('inst_link', models.URLField()),
                ('twt_link', models.URLField()),
                ('wk_link', models.URLField()),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.blogcatgory')),
                ('tages', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.blogtages')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.bloge')),
            ],
        ),
    ]
