# Generated by Django 4.0.2 on 2022-02-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='comments',
        ),
    ]
