# Generated by Django 4.0.2 on 2022-02-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_rename_message_contact_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='comments',
            new_name='message',
        ),
    ]
