# Generated by Django 4.0.2 on 2022-02-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_comments_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='comments',
        ),
    ]
