# Generated by Django 4.0.2 on 2022-02-26 07:32

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('url', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
