# Generated by Django 4.0.2 on 2022-02-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
    ]
