# Generated by Django 4.0.2 on 2022-02-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_videopresentation_delete_video_delete_youtub'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopresentation',
            name='titel',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
